package tn.insat.entities;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Authors generated by hbm2java
 */
@Entity
@Table(name="authors",catalog="bookstoredb")
public class Author  implements java.io.Serializable {

     /**
	 * Generated Serial Version
	 */
	 private static final long serialVersionUID = -4646580628570085708L;

	 @Id
	 @GeneratedValue(strategy=GenerationType.IDENTITY)
     @Column(name="a_author_sk", unique=true, nullable=false)
     private Integer authorId;
    
     @Column(name="a_name", length=45)
     private String name;
    
     @Column(name="a_country", length=45)
     private String country;
    
     @ManyToMany(fetch=FetchType.LAZY)
     @JoinTable(name="book_author", catalog="bookstoredb", joinColumns = { 
         @JoinColumn(name="ba_author_fk", nullable=true, updatable=true) }, inverseJoinColumns = { 
         @JoinColumn(name="ba_book_fk", nullable=true, updatable=true) })
     private Set<Book> books = new HashSet<Book>(0);

    public Author() {
    }
    
    

	public Author(Integer authorId, String name, String country,
			Set<Book> books) {
		super();
		this.authorId = authorId;
		this.name = name;
		this.country = country;
		this.books = books;
	}



	public Author(String name, String country, Set<Book> books) {
		super();
		this.name = name;
		this.country = country;
		this.books = books;
	}



	public Integer getAuthorId() {
		return authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Set<Book> getBooks() {
		return books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

}


