package tn.insat.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Publishers generated by hbm2java
 */
@Entity
@Table(name="publishers")

public class Publisher  implements java.io.Serializable {


	private static final long serialVersionUID = 1093701193930392050L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="p_publisher_sk", nullable=false)
	private int publisherId;

	@Column(name="p_name", nullable=false, length=45)
    private String name;

     
     @OneToMany(fetch=FetchType.LAZY, mappedBy="publisher")
     private Set<Book> books = new HashSet<Book>(0);

    public Publisher() {
    }




	public Publisher(String name, Set<Book> books) {
		super();
		this.name = name;
		this.books = books;
	}




	public int getPublisherId() {
		return publisherId;
	}




	public void setPublisherId(int publisherId) {
		this.publisherId = publisherId;
	}




	public String getName() {
		return name;
	}




	public void setName(String name) {
		this.name = name;
	}




	public Set<Book> getBooks() {
		return books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

}


